name: Release
on:
  push:
    branches: [microsite_action]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - name: Update docs
      run: |
        git config --global user.name "zio-sql Docs"
        git config --global user.email "zio-sql-docs@users.noreply.github.com"
        eval "$(ssh-agent -s)"
#        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        sbt docs/mdoc
        cd website
        yarn install
        yarn deploy
      env:
         TOKEN: ${{ secrets.DEPLOY_KEY }}
         USE_SSH: true
         GIT_USER: git
#    - uses: olafurpg/setup-gpg@v3
#    - name: Publish ${{ github.ref }}
#      run: sbt ci-release
#      env:
#        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
#        PGP_SECRET: ${{ secrets.PGP_SECRET }}
#        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}